# Generated by Django 5.1.1 on 2024-10-23 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_identity_number', models.CharField(blank=True, max_length=10, null=True)),
                ('current_status', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=20)),
                ('cumulative_gpa', models.FloatField(null=True)),
                ('credit_hours', models.IntegerField(null=True)),
                ('eligible_for_application', models.BooleanField(default=False)),
                ('gpa_this_semester', models.FloatField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_date', models.DateField(auto_now_add=True)),
                ('bill_amount', models.FloatField()),
                ('balance', models.FloatField()),
                ('gets_scholarship', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolarship.student')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('scholarship_status', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('can_get_scholarship', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolarship.student')),
            ],
        ),
    ]
